swagger: "2.0"
info:
  title: Calculator Service
  description: Service for multiplying numbers, a Goa teaser
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /add/{a}/{b}:
    get:
      tags:
      - calc
      summary: add calc
      operationId: calc#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        type: integer
      - name: b
        in: path
        description: Right operand
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /divide/{a}/{b}:
    get:
      tags:
      - calc
      summary: divide calc
      operationId: calc#divide
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        type: integer
      - name: b
        in: path
        description: Right operand
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: number
            format: double
      schemes:
      - http
  /multiply/{a}/{b}:
    get:
      tags:
      - calc
      summary: multiply calc
      operationId: calc#multiply
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        type: integer
      - name: b
        in: path
        description: Right operand
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /note/{uuid}:
    get:
      tags:
      - calc
      summary: getNote calc
      operationId: calc#getNote
      parameters:
      - name: uuid
        in: path
        description: The note's UUID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CalcGetNoteResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CalcGetNoteNoteMissingResponseBody'
      schemes:
      - http
    delete:
      tags:
      - calc
      summary: deleteNote calc
      operationId: calc#deleteNote
      parameters:
      - name: uuid
        in: path
        description: The uuid for the note
        required: true
        type: string
      responses:
        "204":
          description: No Content response.
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CalcDeleteNoteNoteMissingResponseBody'
      schemes:
      - http
  /note/create/{userID}:
    post:
      tags:
      - calc
      summary: createNote calc
      operationId: calc#createNote
      parameters:
      - name: userID
        in: path
        description: The UserID for the note
        required: true
        type: string
      - name: CreateNoteRequestBody
        in: body
        description: The Note data to be saved
        required: true
        schema:
          $ref: '#/definitions/CalcCreateNoteRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/CalcCreateNoteResponseBody'
            required:
            - NoteResponse
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CalcCreateNoteBadRequestResponseBody'
      schemes:
      - http
  /notes/{userID}:
    get:
      tags:
      - calc
      summary: getNotes calc
      operationId: calc#getNotes
      parameters:
      - name: userID
        in: path
        description: The email of the user
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CalcGetNotesResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CalcGetNotesNoteMissingResponseBody'
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - calc
      summary: Download ./gen/http/openapi.json
      operationId: calc#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /subtract/{a}/{b}:
    get:
      tags:
      - calc
      summary: subtract calc
      operationId: calc#subtract
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        type: integer
      - name: b
        in: path
        description: Right operand
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
definitions:
  CalcCreateNoteBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: createNote_BadRequest_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CalcCreateNoteRequestBody:
    title: CalcCreateNoteRequestBody
    type: object
    properties:
      Body:
        type: string
        description: The Body of the Note
        example: Dolore qui consequuntur qui dolor.
      Title:
        type: string
        description: The title of the Note
        example: Omnis dolores accusantium doloribus qui.
    example:
      Body: Dolores voluptas suscipit ut rerum odio.
      Title: Ipsum nostrum cumque deserunt labore hic rerum.
  CalcCreateNoteResponseBody:
    title: CalcCreateNoteResponseBody
    type: object
    properties:
      NoteResponse:
        $ref: '#/definitions/NoteResponseResponseBody'
    example:
      NoteResponse:
        UUID: Ea ut enim aut.
    required:
    - NoteResponse
  CalcDeleteNoteNoteMissingResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: deleteNote_NoteMissing_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CalcGetNoteNoteMissingResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: getNote_NoteMissing_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CalcGetNoteResponseBody:
    title: CalcGetNoteResponseBody
    type: object
    properties:
      Note:
        $ref: '#/definitions/NoteResponseBody'
    example:
      Note:
        Body: Ut rerum ipsam eveniet.
        Title: Non quod et facere.
        UUID: Omnis velit laboriosam unde omnis incidunt.
  CalcGetNotesNoteMissingResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: getNotes_NoteMissing_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CalcGetNotesResponseBody:
    title: CalcGetNotesResponseBody
    type: object
    properties:
      notes:
        type: array
        items:
          $ref: '#/definitions/NoteResponseBody'
        description: list of notes
        example:
        - Body: Ut rerum ipsam eveniet.
          Title: Non quod et facere.
          UUID: Omnis velit laboriosam unde omnis incidunt.
        - Body: Ut rerum ipsam eveniet.
          Title: Non quod et facere.
          UUID: Omnis velit laboriosam unde omnis incidunt.
        - Body: Ut rerum ipsam eveniet.
          Title: Non quod et facere.
          UUID: Omnis velit laboriosam unde omnis incidunt.
    example:
      notes:
      - Body: Ut rerum ipsam eveniet.
        Title: Non quod et facere.
        UUID: Omnis velit laboriosam unde omnis incidunt.
      - Body: Ut rerum ipsam eveniet.
        Title: Non quod et facere.
        UUID: Omnis velit laboriosam unde omnis incidunt.
      - Body: Ut rerum ipsam eveniet.
        Title: Non quod et facere.
        UUID: Omnis velit laboriosam unde omnis incidunt.
  NoteResponseBody:
    title: NoteResponseBody
    type: object
    properties:
      Body:
        type: string
        description: The Body of the Note
        example: Excepturi et molestiae aperiam corporis dolore a.
      Title:
        type: string
        description: The title of the Note
        example: Velit consequuntur eum illum voluptatem possimus.
      UUID:
        type: string
        description: The UUID of the created note
        example: Vero itaque.
    example:
      Body: Corrupti molestiae ipsa voluptas impedit dolor.
      Title: Nihil perferendis.
      UUID: Pariatur reiciendis pariatur commodi iusto non accusantium.
  NoteResponseResponseBody:
    title: NoteResponseResponseBody
    type: object
    properties:
      UUID:
        type: string
        description: The UUID of the Created Note
        example: Consequatur rerum est nostrum qui aut vero.
    example:
      UUID: Labore dolores eveniet.
